[package]
name = "sendsecure"
version = "0.1.0"
authors = ["Allan Seymour <banks.the.megalithic.stone@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.22"
hyper = "0.9.14"
url = "1.2.4"
mime = "0.2.2"
mime_multipart="0.3.5"
mime_guess="1.8.1"
