[package]
name = "sendsecure-rs"
version = "0.1.0"
authors = ["Allan Seymour <banks.the.megalithic.stone@gmail.com>"]

[dependencies]
rustc-serialize = "0.3.22"
hyper = "0.9.14"
url = "1.2.4"
multipart = "0.9.0-alpha.9"
mime = "0.2.2"
